language: clojure
script: lein test

before_script:
  - npm install -g bower

env:
  global:
  - secure: gUiG4z3HeitrQgMLomkZlLeLAUf3kV4UJW4KoauiPkOjlPvaLVZP132LXQVIzQXX6OnFC/IDuLhY1yOS9dkDJT7xXggsq513/gVWCNz1mBKp/Erp2eQ99G9NQUIdwIECr2+16RDsv9kYpDxEl8pLzgEBr9M8Cm7cWdt8pNVV2ZY=
  - secure: vbyZ+Pf0tLd1R17sQ2W4CPgtVFPtgQYmmBpo6eVXmc3G8aqHSQxc+Sdf6Yn8qDqs1V//Sv+J9ajXjCqIjYhRZk99eLDLSM0q3J8OrTQRhff2KuDXbznPlu7A84vX7UEpf2t16ReN42Q/DChyhJwwNixTR4qAMYwtjftgchhAsQg=

after_success:
  - test $TRAVIS_BRANCH == "release" && lein ci-deploy
  #- test $TRAVIS_BRANCH == "master" && lein ci-deploy-test
