language: clojure
script: lein ci
before_install:
- sudo apt-get install nodejs
- sudo apt-get install npm
- npm install -g bower
env:
  global:
  - secure: gUiG4z3HeitrQgMLomkZlLeLAUf3kV4UJW4KoauiPkOjlPvaLVZP132LXQVIzQXX6OnFC/IDuLhY1yOS9dkDJT7xXggsq513/gVWCNz1mBKp/Erp2eQ99G9NQUIdwIECr2+16RDsv9kYpDxEl8pLzgEBr9M8Cm7cWdt8pNVV2ZY=
  - secure: vbyZ+Pf0tLd1R17sQ2W4CPgtVFPtgQYmmBpo6eVXmc3G8aqHSQxc+Sdf6Yn8qDqs1V//Sv+J9ajXjCqIjYhRZk99eLDLSM0q3J8OrTQRhff2KuDXbznPlu7A84vX7UEpf2t16ReN42Q/DChyhJwwNixTR4qAMYwtjftgchhAsQg=
